export const users = [
    {
      nombre: "Guillermo Grimes",
      email: "ggrimes@mail.com",
      password: "98745",
      rol: "user",
      id: 1,
    },
    {
      nombre: "Norris Gorczany",
      email: "ngor@mail.com",
      password: "98745",
      rol: "user",
      id: 2,
    },
    {
      nombre: "Richmond Rutherford",
      email: "rrutherford@mail.com",
      password: "98745",
      rol: "user",
      id: 3,
    },
    {
      nombre: "Valentina Haag",
      email: "valhaag@mail.com",
      password: "98745",
      rol: "user",
      id: 4,
    },
    {
      nombre: "Herminio King",
      email: "hking@mail.com",
      password: "98745",
      rol: "user",
      id: 5,
    },
    {
      nombre: "Paula Rodriguez",
      email: "prodriguez@mail.com",
      password: "98745",
      rol: "user",
      id: 6,
    },
    {
      nombre: "Demond Runolfsdottir",
      email: "demond@mail.com",
      password: "98745",
      rol: "user",
      id: 7,
    },
    {
      nombre: "Stanley Dibbert",
      email: "standib@mail.com",
      password: "98745",
      rol: "user",
      id: 8,
    },
    {
      nombre: "Kole Borer",
      email: "borerk@mail.com",
      password: "98745",
      rol: "user",
      id: 9,
    },
    {
      nombre: "Opal Lynch",
      email: "opalynch@mail.com",
      password: "98745",
      rol: "user",
      id: 10,
    },
    {
      nombre: "Einar Kuvalis",
      email: "eikuv@mail.com",
      password: "98745",
      rol: "user",
      id: 11,
    },
    {
      nombre: "Lukas Wyman",
      email: "lwyman@mail.com",
      password: "98745",
      rol: "user",
      id: 12,
    },
    {
      nombre: "Lottie Larkin",
      email: "llark@mail.com",
      password: "98745",
      rol: "admin",
      id: 13,
    },
  ];